### PR TITLE
Added support for other image types

### PR DESCRIPTION
**Pull request by bitwiseman**
@oleg-nenashev 
Targets https://github.com/jenkins-infra/jenkins.io/pull/1168 .

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
СС @rtyler
I used Jenkins on a blue background for a reason in order to make it fit better to the site. @bitwiseman  do you prefer the official logo? I started from it and didn't like it

**Comment by bitwiseman** [comment]
@oleg-nenashev 
Yeah, you're right the actual logo isn't the right thing.  
Not to speak negatively of the work you did, but I didn't love that either. 
How about a line drawing version of the logo?

**Comment by oleg-nenashev** [comment]
@bitwiseman I would appreciate a screenshot :)

**Comment by bitwiseman** [comment]
screen shot 2017-10-31 at 2 43 45 pm

**Comment by oleg-nenashev** [comment]
The idea was to have 128x128 logo, but maybe it's fine to have it a bit higher.

Or maybe just something like https://www.tribearound.com/static/img/no_user_logo.jpeg for starters?

**Comment by oleg-nenashev** [comment]
Anyway, let's take the current PR to move forward

**Pull request merged**
